### ISSUE TITLE
Link glossary to svg components

### ISSUE THREAD

**Issue by collinschwantes** [collinschwantes/Annotated_Ultras#13]
Since many definitions depend on knowing the position of one feature relative to another, it would be beneficial to link components of the definition that are delineated in the svg to the glossary text. Would that just require href? @gemfarmer

**Comment by gemfarmer** [comment]
As in  "X is part of Y and below Z"? Or are we talking numbers. I guess I am a little confused here. We should chat about it.

**Comment by collinschwantes** [comment]
_Example def_: **Metapleural carina**: The carina that delimits the **metapleuron** dorsally from the **propodeum**, extends from just ventral of the metapleural arm to the metacoxal articulation and passes anteroventral to the propodeal spiracle.

Each bolded term is defined in svg. If you click on the term in the definition, it will be highlighted on the image.  I was thinking we could use the lo-dash list we created to look for defined terms and some JS to process the definitions so that on click they change the class of the defined term. This is not an urgent thing.

**Comment by collinschwantes** [comment]
I get less and less interested in this as the days pass...

**Comment by gemfarmer** [comment]
hahah. It sounds like a good idea though. I have hit a rough patch with work and the housing stuff, but I'll take a look some time in the near future/.

**Comment by collinschwantes** [comment]
Thanks Brian, I'll be starting my new position in 8 days!
