### ISSUE TITLE
Need to figure out where to host

### ISSUE THREAD

**Issue by collinschwantes** [collinschwantes/Annotated_Ultras#17]
@gemfarmer what do you think the sites will require for hosting?

**Comment by gemfarmer** [comment]
I think the only thing that we need to add is a `CNAME` file with the domain on it. And to register the IP associated with the github pages endpoint with a DNS service

**Comment by gemfarmer** [comment]
- https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
- https://help.github.com/articles/setting-up-your-pages-site-repository/

**Comment by collinschwantes** [comment]
I think a github organization would be the way to go. It allows users to build sites without installing jekyll, it keeps everything in a central location, and it means that we can add pages that help people understand what is going.
