### ISSUE TITLE
Create Panel to display HAO information

### ISSUE THREAD

**Issue by collinschwantes** [collinschwantes/Annotated_Ultras#3]
Need to create a panel to display HAO information that hides when no information is to be displayed and that creates a list of definitions for that session. EG if a person clicks on multiple body parts and asks for multiple definitions there should be a list for defs (techincally we want concpets but w/e)
- [Head](http://api.hymao.org/public/ontology_class/show_expanded/469)
  - The tagma that is located anterior to the **thorax**. (ideally each anatomical term in here would be linked to the svg and highlight that section when clicked)

**Comment by gemfarmer** [comment]
Hmm. I can take a look later. Getting it to highlight the correct part of the svg seems like it could be tricky. Basically, it will become very important to make sure that each anatomical unit that is clickable will need to have its own `<path>`. The clicking and panel part should be pretty straight forward though, and maybe what we need to focus on now.

**Comment by gemfarmer** [comment]
I think what we will want to do now, is add a class to a given demo clickable part like so:
HTML

```
<section class="panel">
  <h1>Definition List</h1>
  <ul class="panel-definition_list>
    <li class="panel-definition>
         Dummy defintion. Should be more complicated than this.
   </li>
  <li class="panel-definition" data-defintion="some-body-part" aria-hidden="true">
       Dummy Definition
  </li>
  </ul>
</section>
...
<path class="clickable-part" data-bodypart="some-body-part"></path>

```

then, in the js, hook into it

JS

```
$('.clickable-part).on('click', function(event) {
  var target = event.target;
  var bodyPartName = $.data(target, 'bodypart'); 
  var selector = '.panel-definition[' + bodyPartName + ']'; 
  $(selector).attr('aria-hidden', false);
}

```

CSS

```
.panel-definition {
  display: inline-block;
}

.panel-definition[aria-hidden=true] {
  display: none;
}
```

**Comment by gemfarmer** [comment]
@collinschwantes This is roughly what needs to be done ^^

**Comment by collinschwantes** [comment]
Works very well! 

I've made a csv file with all defs for anatomical features called _HAO_terms.csv_. It has the following columns:
- **term**
- **concept** (ontological definition)
- **uri** (permanent web address)
- reference (who defined it, probably don't care about this for the app) 

I plan on using [Papa Parser](http://papaparse.com/) to parse the csvs then your function to generate the formatted defs. The documentation for Papa Parser makes me happy.

> "Great, but I have a file to parse."
> 
> Then give Papa a File instead of a string. Since file parsing is asynchronous, don't forget a callback.

This should make getting the desired format easier.

**Comment by collinschwantes** [comment]
Also, how do we hide the glossary when all elements are hidden?

**Comment by gemfarmer** [comment]
The best approach to hiding the glossary when all the elements are hidden would be to create an object that would manage the "state" of the glossary. Basically which ones are currently hidden or not. And hide it if all are hidden. I have a little time before work, so I'll try to put something together quick.
