### ISSUE TITLE
Terms not in the json file break the glossary function

### ISSUE THREAD

**Issue by collinschwantes** [collinschwantes/Annotated_Ultras#8]
If an ID is not in the JSON file and is clicked, the glossary toggle class function becomes locked in the hidden class.

**Comment by collinschwantes** [comment]
We should maybe use \* wildcard to avoid cases of mis-matched cases. Misspelled IDs in the SVG might be problematic, I'll dry to develop a programatic way to input id and class tags for the different svg groups. Shouldnt be hard since we already have a text element with the same name.

**Comment by collinschwantes** [comment]
Its easy enough to change xml attributes in inkscape, so setting class and ID as you go is no problem.

**Comment by gemfarmer** [comment]
I think it will definitely be smart to have number-based IDs.

**Comment by collinschwantes** [comment]
Probably true- they probably exist in the ontology that the concepts come
from

On Monday, February 22, 2016, Brian Hedberg notifications@github.com
wrote:

> I think it will definitely be smart to have number-based IDs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/collinschwantes/Annotated_Ultras/issues/8#issuecomment-187025452
> .

## 

_Collin Schwantes_
Spatial Ecologist
2500 Wisconsin Ave NW
Washington, DC 20007
http://collinschwantes.github.io/
